### ISSUE TITLE
Make advanced options discoverable

### ISSUE THREAD

**Issue by kingosticks** [guysoft/pi-imager#3]
Originally submitted by @Timmmm at https://github.com/raspberrypi/rpi-imager/issues/180. Reproducing the main gist here because it has a better chance of being implemented. Another copy of the idea is also worthwhile incase the original one is deleted without warning or reason. 

**Timmmm:**
> I submitted two issues (#178 and #179) to do automatic setup of SSH and wifi. Turns out that feature already exists, which is fantastic!
>
>Unfortunately it's completely undiscoverable. There's no way to know it exists unless you magically already know.
>
>There should be some visual indication that the option is available - "do you want to set up advanced options?" sort of thing.

----
**lurch:**
> This got discussed in the blog-comments https://www.raspberrypi.org/blog/raspberry-pi-imager-update-to-v1-6/

----

**maxnet:**
> The shortcut sort of was the middle ground.
Between team #we-are-targetting-beginners rejecting the concept of a button, and team #experts coming up with a command line option (which is non-trivial to use on say Mac OS X).

----
**kingosticks:**
> So to clarify, is a button with a very clear warning really off the table? Such a button could be small and placed in the bottom corner to reduce the chance of being accidentally pressed. Something like this:
>
> 
![113156864-4c3cb880-9232-11eb-841e-7f94cbc32fa9](https://user-images.githubusercontent.com/934824/151987896-c4a2a594-9032-4db7-93c1-16025b602794.png)

>
> If someone still feels this could lead to anyone accidentally changing the advanced options, what if one of the advanced options was to always show this button? So then you only have to remember/lookup the magic shortcut once. If that is still somehow disagreeable, you could have the button hidden unless the --show-advanced-options command line option is used (for the benefit of non-Mac OS users only).
>
> I'm really struggling to see how this adjustment makes the tool noticeably more confusing for new users. And it's much better for those other users who do want to easily enable SSH, change the hostname, configure WiFi etc.
>
> Would you accept a pull request with such a change?

**ghollingworth:**
> For the moment we've already made our decision about how we're going to support this functionality. As said many times before we do not want to change the user interface at the moment since this is the easiest way for people to image SD cards.
>
> When an easier way appears we may then make this a more complex interface for more advanced users, but until then we will not be changing it.
> 
> You are free to build and distribute your own version (as long as you remove the Raspberry Pi logos and wordmark from the front page.)

**Comment by kingosticks** [comment]
Turns out they did this already in secret! What an interesting example of how to run a project.

**Comment by Timmmm** [comment]
Maybe it was deliberately hidden in that commit by one contributor so they didn't have to get shut down by the "beginners will want to set up WiFi manually via wpa_supplicant.conf" argument. Or maybe they realised how silly that argument was but didn't want to admit it. Who knows! Glad they finally fixed it anyway.

**Comment by kingosticks** [comment]
Seems like the latter, the author is an employee. It's frustrating to have our time wasted but there you go, you live and learn who to work with. If I have any more imager contributions I'll be submitting them to this project. 

EDIT: Man, I am so bitter these days. Sorry, World!
