### ISSUE TITLE
Remove Telemetry?

### ISSUE THREAD

**Issue by kingosticks** [guysoft/pi-imager#4]
Does it make sense to keep the telemetry? Would be sad to upset the RPi team with stuff they don't want.

**Comment by guysoft** [comment]
I guess that makes a good idea.
I say we first get CI/CD working on enough distros so its easy to release and then ask them once this repo is useful.

**Comment by guysoft** [comment]
Well its back in question.
@ghollingworth do you guys have any preference? 
Persnoally I don't mind leaving it on if it gives us statistics and if some image becomes popular

**Comment by ghollingworth** [comment]
Indeed, leaving it in would enable you to look at the stats, you could also change the version numbering scheme to identify your version as separate from the rpi-imager version (i.e. use guysoft-1.7.1 for example).

Gordon

**Comment by guysoft** [comment]
Thanks for the info. I might change the version name so it does not mix.
Will see when I have time to dig in to that

**Comment by guysoft** [comment]
Just to note the 1.7.**1** is currently hardcoded:
```cmake
set(IMAGER_VERSION_MAJOR 1)
set(IMAGER_VERSION_MINOR 7)
set(IMAGER_VERSION_STR "${IMAGER_VERSION_MAJOR}.${IMAGER_VERSION_MINOR}.1")
set(IMAGER_VERSION_CSV "${IMAGER_VERSION_MAJOR},${IMAGER_VERSION_MINOR},1,0")
add_definitions(-DIMAGER_VERSION_STR="${IMAGER_VERSION_STR}")
add_definitions(-DIMAGER_VERSION_CSV=${IMAGER_VERSION_CSV})
```

Note in windows the FILEVERSION and PRODUCTVERSION have to be numbers.

I am changing to ``1.7.1-unofficial``.

**Comment by guysoft** [comment]
Done: https://github.com/guysoft/pi-imager/releases
