### ISSUE TITLE
Typo.

### ISSUE THREAD

**Issue by litecave** [guysoft/pi-imager#7]
Hello. List of typo.
1. Unfficial (unofficial)
2. Mainatained (maintained).
![image](https://user-images.githubusercontent.com/64094645/157195783-1b826073-2f44-4bd4-8b2c-42f6a98b6f84.png)

**Comment by litecave** [comment]
![image](https://user-images.githubusercontent.com/64094645/157206761-25f166ca-9751-48f3-93fc-24e48c8768e7.png)
3. PlermoaPi (PleromaPi)

**Comment by guysoft** [comment]
Thanks for the proof reading. 
Fixed with: https://github.com/guysoft/pi-imager-web/commit/531d28545ff1bb665547e8fd1d6c9a9bb24c4bbe
Deployed successfully
